# Generated by Django 4.0.1 on 2022-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('static', 'static application'), ('dynamic', 'web application')], max_length=30, null=True),
        ),
    ]
